spring.application.name=OrderUpdateService
server.port=8081
spring.application.admin.enabled=false

file.path=C:/Users/Lenovo/Downloads/order_updates.csv
position.maintained.service.url=http://localhost:8080/position/maintaining
